### ISSUE TITLE
GIt status not updating

### ISSUE THREAD

**Issue by allanabiud** [imsi32/yatline-githead.yazi#1]
Entering a git repository from inside yazi doesn't show the git status information. I have to open yazi from the git repository for the information to appear and leaving the directory doesn't remove the information.

**Comment by imsi32** [comment]
Strange, it also works that way for me. Can you give the output of following command in some git directory:
``` bash
LANGUAGE=en_US.UTF-8 git status --ignore-submodules=dirty --branch --show-stash --ahead-behind 2>/dev/null
```
And can you check if [githead.yazi](https://github.com/llanosrocas/githead.yazi) is working correctly. (Which this plugin is based on)

**Comment by allanabiud** [comment]
> Strange, it also works that way for me. Can you give the output of following command in some git directory:
> 
> ```shell
> LANGUAGE=en_US.UTF-8 git status --ignore-submodules=dirty --branch --show-stash --ahead-behind 2>/dev/null
> ```
> 
> And can you check if [githead.yazi](https://github.com/llanosrocas/githead.yazi) is working correctly. (Which this plugin is based on)

Here is the output
```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   i3/.config/i3/config
        modified:   yazi/.config/yazi/keymap.toml
        modified:   yazi/.config/yazi/yazi.toml
        modified:   zsh/.config/zsh/.zshrc

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        yazi/.config/yazi/init.lua
        yazi/.config/yazi/package.toml
        yazi/.config/yazi/plugins/
        zsh/.config/zsh/.yazi.sh

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by allanabiud** [comment]
> Strange, it also works that way for me. Can you give the output of following command in some git directory:
> 
> ```shell
> LANGUAGE=en_US.UTF-8 git status --ignore-submodules=dirty --branch --show-stash --ahead-behind 2>/dev/null
> ```
> 
> And can you check if [githead.yazi](https://github.com/llanosrocas/githead.yazi) is working correctly. (Which this plugin is based on)

And yes, [githead.yazi](https://github.com/llanosrocas/githead.yazi) also works the same way.

**Comment by allanabiud** [comment]
After updating yazi, it seems to be working fine now

**Comment by imsi32** [comment]
Good to hear that I wasn't sure where the problem is coming from.
